blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostsView.as_view(), name='posts'),
    path('post/<slug:post_slug>/', views.detail_post, name='detail_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/<slug:post_slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('categories_list/', views.categories_list, name='categories_list'),
    path('by_category/<slug:category_slug>/', views.ByCategory.as_view(), name='by_category'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('search/', views.SearchView.as_view(), name='search_list'),
    path('like/<slug:slug>/', views.like_post, name='like_post'),
    path('about/', views.AboutView.as_view(), name='about'),
    
    path('user_posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path('user_detail_post/<slug:post_slug>/', views.user_detail_post, name='user_detail_post'),
    path('delete_comment/<int:pk>/', views.delete_commet, name='delete_comment'),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.AllView, name='allview'),

    path('request_course_save/', views.sign_course_post, name='sign_course'),
    path('msg_save/', views.msg_save, name='msg_save'),

    path('edit/', views.edit, name='edit'),
    path('edit/journal/', views.JournalView, name='journal'),
    path('edit/messages/', views.ContactMsgView.as_view(), name='contact_msg'),
    path('edit/course_messages/', views.SignMsgView.as_view(), name='sign_msg'),

    path('user_page/<int:pk>/', views.UserPageView.as_view(), name='user_page'),
    path('user_page/user_edit/<int:pk>/', views.user_edit, name='user_edit'),
    path('user_page/user_edit/user_journal/<int:pk>/', views.UserJournalView, name='user_journal'),

    path('user/edit/add_student/', views.StudenView.as_view(), name='add_student'),
    path('user/edit/add_teacher/', views.TeacherView.as_view(), name='add_teacher'),
    path('user/edit/add_group/', views.GroupView.as_view(), name='add_group'),
    path('user/edit/add_course/', views.CourseView.as_view(), name='add_course'),
    path('user/edit/add_gallery/', views.GalleryView.as_view(), name='add_gallery'),
    path('user/edit/add_location/', views.LocationView.as_view(), name='add_location'),
    path('edit/add_social/', views.AddSocialView.as_view(), name='add_social'),

    path('user/edit/update_course/<int:pk>/', views.UpdateCourseView.as_view(), name='update_course'),
    path('user/edit/update_teacher/<int:pk>/', views.UpdateTeacherView.as_view(), name='update_teacher'),
    path('user/edit/update_location/<int:pk>/', views.UpdateLocationView.as_view(), name='update_location'),
    path('user/edit/update_gallery/<int:pk>/', views.UpdateGalleryView.as_view(), name='update_gallery'),
    path('user/edit/journal/update_student/<int:pk>/', views.UpdatePupilView.as_view(), name='update_student'),
    path('user/edit/journal/update_social/<int:pk>/', views.update_social, name='update_social'),
    path('user/edit/update_group/<int:pk>/', views.UpdateGroupView.as_view(), name='update_group'),
    
    path('delete/course/<int:pk>/', views.DelCourseView.as_view(), name='delete_course'),
    path('delete/teacher/<int:pk>/', views.DelTeacherView.as_view(), name='delete_teacher'),
    path('delete/gallery/<int:pk>/', views.DelGalleryView.as_view(), name='delete_gallery'),
    path('delete/location/<int:pk>/', views.DelLocationView.as_view(), name='delete_location'),
    path('delete/group/<int:pk>/', views.DelGroupView.as_view(), name='delete_group'),
    path('delete/social/<int:pk>/', views.del_social, name='delete_social'),
    path('delete/student/<int:pk>/', views.DelStudentView.as_view(), name='delete_student'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('thereisno_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('mainapp.urls')),
    path('account/', include('registration.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('landing_page/', include('landingpage.urls')),
    path('gallery/', include('gallery.urls')),

]

handler404 = 'mainapp.views.my_error404'
handler403 = 'mainapp.views.my_error403'
handler500 = 'mainapp.views.my_error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpage/models.py
from django.db import models
import datetime
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
# Create your models here.


class CourseImage(models.Model):
    name = models.CharField(max_length=20)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=30)
    image = models.ForeignKey(CourseImage, blank=True, null=True, on_delete=models.PROTECT)
    who_can = models.CharField(max_length=255)
    countinue = models.CharField(max_length=255)
    level = models.CharField(max_length=255)
    price = models.PositiveIntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Location(models.Model):
    image = ThumbnailerImageField(resize_source={'size': (400, 0), 'crop':'scale', 'quantity':90}, upload_to='landingpage/location/')
    street = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    subway = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class Gallery(models.Model):
    
    image = models.ImageField(upload_to='landingpage/gallery/')
    description = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)




class Teacher(models.Model):
    name = models.CharField(max_length=30)
    image = ThumbnailerImageField(resize_source={'size': (400, 0), 'crop':'scale', 'quantity':90},upload_to='landingpage/teacher/', blank=True, null=True)
    expirience = models.CharField(max_length=255)
    strong_side = models.CharField(max_length=255)
    achievement = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Group(models.Model):
    LEVEL = (
        (None, 'LEVEL'),
        ('A1', 'A1'),
        ('A2', 'A2'),
        ('B1', 'B1'),
        ('B2', 'B2'),
        ('C1', 'C1'),
        ('C2', 'C2'),
    )
    DAYS_OF_WEEK = (
        (None, "Days of week"),
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
    )
    lesson_time = models.TimeField()
    days_of_week = MultiSelectField(choices=DAYS_OF_WEEK, max_length=10, max_choices=3)
    teacher = models.ForeignKey('Teacher', on_delete=models.PROTECT)
    level = models.CharField(max_length=2, choices=LEVEL)
    creaded_at = models.DateField(auto_now_add=True)
    exists = models.BooleanField(default=0)
    name = models.CharField(max_length=20, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

        
class Pupil(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    phone = models.PositiveIntegerField(unique=True)
    birth = models.DateField()
    group = models.ForeignKey(Group, on_delete=models.PROTECT)
    paid = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s' % (self.name, self.surname)

    def age(self):
        age = datetime.date.today().year - int(self.birth.strftime('%Y'))
        return age




# Social name -----------------------------------------------------------------------
class SocialName(models.Model):
    name = models.CharField(max_length=40)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# Links for Social name ----------------------------------------------------------------
class Links(models.Model):
    name = models.ForeignKey(SocialName, on_delete=models.CASCADE)
    links = models.URLField(blank=True, null=True)


# Message -------------------------------------------------
class ContactMsg(models.Model):
    name = models.CharField(max_length=50)
    phone = models.PositiveBigIntegerField()
    sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.name, self.phone)
    
    class Meta:
        ordering = ['-sent']


# sign up to course-------------------------------------------
class SingCourse(models.Model):
    LEVEL = (
        (None, 'LEVEL'),
        ('A1', 'A1'),
        ('A2', 'A2'),
        ('B1', 'B1'),
        ('B2', 'B2'),
        ('C1', 'C1'),
        ('C2', 'C2'),
    )
    name = models.CharField(max_length=50)
    phone = models.PositiveBigIntegerField(help_text='123456789')
    sent = models.DateTimeField(auto_now_add=True)
    level = models.CharField(max_length=2, choices=LEVEL)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' % (self.name, self.phone)

landingpage/forms.py
from dataclasses import field
from django import forms

from .models import Pupil, Teacher, Gallery, Group, Course, Location, ContactMsg, SocialName, Links, SingCourse



class PupilForm(forms.ModelForm):
    class Meta:
        model = Pupil
        exclude = '__all__'
        widgets = {
            'birth': forms.DateInput(attrs={'type': 'date'}),
            'author': forms.HiddenInput
        }

        
class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput
        }

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'lesson_time': forms.TimeInput(attrs={'type': 'time'}),
            'author': forms.HiddenInput

        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput
        }


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput
        }
        

class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput
        }
        

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMsg
        fields = '__all__'


SocialForm = forms.modelform_factory(SocialName, fields='__all__', widgets = {'author': forms.HiddenInput})
LinksForm = forms.inlineformset_factory(SocialName, Links, fields='__all__', extra=5, can_delete_extra=False)


class SignCourseForm(forms.ModelForm):
    class Meta:
        model = SingCourse
        fields = '__all__'

        widgets = {
        }

landingpage/templates/landingpage/landingpage_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::Add new</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_add.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>

<body>
    <div class="container">

        <section>
            <ul class="navbar">
                <li class="nav-item"><a href="{% url 'landingpage:allview' %}"
                        class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:user_edit' user.pk %}"
                        class="nav-link">Edit</a></li>
            </ul>
        </section>
        <section class="add-form">
            
            {% if messages %}
            {% for message in messages %}
            <div class="message">
                {{ message }}
                <span class="closebtn"
                    onclick="this.parentElement.style.display='none';">&times;</span>
            </div>
            {% endfor %}
            {% endif %}

            <h1>Add {{ add }}</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Add" class="btn">
            </form>
        </section>
    </div>
</body>

</html>

landingpage/templates/landingpage/landingpage_add_social.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::Add new</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_add.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>

<body>
    <div class="container">

        <section>
            <ul class="navbar">
                <li class="nav-item"><a href="{% url 'landingpage:allview' %}"
                        class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:user_edit' user.pk %}"
                        class="nav-link">Edit</a></li>
            </ul>
        </section>
        <section class="add-form">
            
            {% if messages %}
            {% for message in messages %}
            <div class="message">
                {{ message }}
                <span class="closebtn"
                    onclick="this.parentElement.style.display='none';">&times;</span>
            </div>
            {% endfor %}
            {% endif %}

            <h1>Add Instagra, Telegram, Facebook, ...</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ social_form }}
                {{ links_form }}
                <input type="submit" value="Add" class="btn">
            </form>
        </section>
    </div>
</body>

</html>

landingpage/templates/landingpage/landingpage_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::Journal and messages</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_edit.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>
<body>
    <div class="container">
        <section class="navbar">
            <ul class="nav">
                <li class="nav-item"><a href="{% url 'landingpage:allview'%}#menu" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:journal' %}" class="nav-link">Journal</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:contact_msg' %}" class="nav-link">Messages</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:sign_msg' %}" class="nav-link">Course messages</a></li>
            </ul>
        </section>
    </div>
    
</body>
</html>

landingpage/templates/landingpage/landingpage_edit_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::Edit</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_edit.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>
<body>
    <div class="container">
        <section class="navbar">
            <ul class="nav">
                <li class="nav-item"><a href="{% url 'landingpage:allview'%}#menu" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:user_page' user.pk %}" class="nav-link">Your page</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:user_journal' user.pk %}" class="nav-link">Journal</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_student' %}" class="nav-link">Add student</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_teacher' %}" class="nav-link">Add teacher</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_group' %}" class="nav-link">Create group</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_course' %}" class="nav-link">Add course</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_location' %}" class="nav-link">Add location</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_gallery' %}" class="nav-link">Add Gallery</a></li>
                <li class="nav-item"><a href="{% url 'landingpage:add_social' %}" class="nav-link">Add Social</a></li>
            </ul>
        </section>
    </div>
    
</body>
</html>

landingpage/templates/landingpage/sign_msg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::C Messages</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_course_msg.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>

<body>
    <div class="container">

        <section>
            <ul class="navbar">
                <li class="nav-item"><a href="{% url 'landingpage:allview' %}"
                        class="nav-link">Home</a></li>
                <li class="nav-item"><a {% if user.is_authenticated %}
                        href="{% url 'landingpage:user_edit' user.pk %}" {% else %}
                        href="{% url 'landingpage:edit' %}" {% endif %} class="nav-link">Edit</a>
                </li>
            </ul>
        </section>
        <section class="contact-msg">
            <h1>Messages<h1>
                    {% if msgs %}
                    {% for m in msgs %}
                    <div class="cart">
                        <p>
                            <span><strong>Name:</strong>{{ m.name }}</span>
                            <span><strong>Phone:</strong>{{ m.phone }}</span>
                            <span><strong>Level:</strong>{{ m.level }}</span>
                            <span><strong>Course:</strong>{{ m.course }}</span>
                            <span><strong>Sent:</strong>{{ m.sent }}</span>
                        </p>

                    </div>
                    {% endfor %}
                    {% else %}
                    <h1>Empty</h1>
                    {% endif %}
        </section>
    </div>
</body>

</html>

landingpage/templates/landingpage/user_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course::User page</title>
    <link rel="stylesheet" href="{% static 'css/landingpage_user.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon-32x32.png' %}" type="image/x-icon">

</head>

<body>
    <div class="container">


        <section class="header" id="header">
            

            {% if messages %}
            {% for message in messages %}
            <div class="message">
                {{ message }}
                <span class="closebtn"
                    onclick="this.parentElement.style.display='none';">&times;</span>
            </div>
            {% endfor %}
            {% endif %}
            <h1 id="menu">Menu: {{ user.username }}</h1>
            <ul>
                <li><a href="{% url 'landingpage:allview' %}">Home</a></li>
                <li><a href="#courses">Courses</a></li>
                <li><a href="#teachers">Teachers</a></li>
                <li><a href="#gallery">Gallery</a></li>
                <li><a href="#location">Location</a></li>
                <li><a href="#social">Social</a></li>
                <li><a href="{% url 'landingpage:user_edit' user.pk %}">Edit</a></li>
            </ul>
        </section>


        <section class="courses" id="courses">
            {% if courses %}
            {% for course in courses %}
            <div class="course-card">
                <div class="card">
                    <table class="course-table">
                        <thead>
                            <tr>
                                <th colspan="3">
                                    {{ course.image.icon|safe }}
                                </th>

                            </tr>
                            <tr>
                                <th colspan="3">
                                    {{ course.name }}
                                </th>
                            </tr>
                        </thead>

                        <tbody class="course-tbody">
                            <tr>
                                <th><i class="bi bi-flag"></i></i></th>
                                <th>Who can:</th>
                                <td>{{ course.who_can }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-clock-history"></i></th>
                                <th>Countinue:</th>
                                <td>{{ course.countinue }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-bar-chart-line-fill"></i></th>
                                <th>Level:</th>
                                <td>{{ course.level }}</td>
                            </tr>
                        </tbody>

                        <tfoot class="course-tfoot">
                            <tr>
                                <th colspan="3">
                                    <h3>{{ course.price }}$</h3>
                                </th>
                            </tr>
                            <tr class="edit_del_course">
                                <td colspan="2">
                                    <a
                                        href="{% url 'landingpage:update_course' course.pk %}">Update</a>
                                </td>

                                <td colspan="1">
                                    <a
                                        href="{% url 'landingpage:delete_course' course.pk %}">Delete</a>
                                </td>
                            </tr>
                        </tfoot>

                    </table>

                </div>
            </div>
            {% endfor %}

            {% else %}
            <h1 class="empty">Empty</h1>
            {% endif %}

        </section>



        <section class="teachers" id="teachers">
            {% if teachers %}
            {% for teacher in teachers %}
            <div class="teacher-card">
                <div class="card">
                    <table class="table-teacher">
                        <thead class="teacher-thead">
                            <tr>
                                <th colspan="3">
                                    {% if teacher.image %}
                                    <img src="{{ teacher.image.url }}" alt="">
                                    {% endif %}
                                </th>

                            </tr>
                            <tr>
                                <th colspan="3">
                                    {{ teacher.name }}
                                </th>
                            </tr>
                        </thead>

                        <tbody class="teacher-tbody">
                            <tr>
                                <th><i class="bi bi-clipboard2-data"></i></th>
                                <th>Expirience:</th>
                                <td>{{ teacher.expirience }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-bag-plus"></i></th>
                                <th>Achievement:</th>
                                <td>{{ teacher.achievement }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-boxes"></i></th>
                                <th>Strong side:</th>
                                <td>{{ teacher.strong_side }}</td>
                            </tr>
                        </tbody>
                        <tfoot class="teacher-tfoot">
                            <tr class="edit_del_teacher">
                                <td colspan="2">
                                    <a
                                        href="{% url 'landingpage:update_teacher' teacher.pk %}">Update</a>
                                </td>

                                <td>
                                    <a
                                        href="{% url 'landingpage:delete_teacher' teacher.pk %}">Delete</a>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            {% endfor %}

            {% else %}
            <h1 class="empty">Empty</h1>
            {% endif %}
        </section>

        <section class="gallery" id="gallery">
            {% if gallery %}

            {% for g in gallery %}
            <figure>
                <!-- Trigger the Modal -->
                <a href="#{{ g.id }}">
                    <img id="myImg" src="{{ g.image.url }}" alt="" width="300px">
                </a>
                <div class="edit_del_gallery">
                    <a href="{% url 'landingpage:update_gallery' g.pk %}">Update</a>
                    <a href="{% url 'landingpage:delete_gallery' g.pk %}">Delete</a>
                </div>
            </figure>

            <!-- The Modal -->
            <div id="{{ g.id }}" class="modal">

                <!-- The Close Button -->
                <a href="#" class="close">&times;</a>

                <!-- Modal Content (The Image) -->
                <img class="modal-content" id="{{ g.id }}" src="{{ g.image.url }}">

                <!-- Modal Caption (Image Text) -->
                <div id="caption">{{ g.description }}</div>
            </div>
            {% endfor %}

            {% else %}
            <h1 class="empty">Empty</h1>
            {% endif %}
        </section>

        <section class="contact" id="location">
            {% if location %}
                    {% for address in location %}
            <div class="contact-card">
                <div class="card">
                    
                    <table class="table-location">
                        <tbody class="location-tbody">
                            <tr class="md">
                                <th class="img" colspan="3">
                                    {% if address.image %}
                                    <img src="{{ address.image.url }}" alt="">
                                    {% endif %}
                                </th>
                            </tr>
                            <tr>
                                <th class="img lg" colspan="3" rowspan="4">
                                    {% if address.image %}
                                    <img src="{{ address.image.url }}" alt="">
                                    {% endif %}
                                </th>
                            </tr>
                            <tr>
                                <th><i class="bi bi-geo-alt-fill"></i></th>
                                <th> Street:</th>
                                <td>{{ address.street }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-alt"></i></th>
                                <th>Subway:</th>
                                <td>{{ address.subway }}</td>
                            </tr>
                            <tr>
                                <th><i class="bi bi-compass"></i></th>
                                <th>address:</th>
                                <td>{{ address.address }}</td>
                            </tr>
                        </tbody>

                        <tfoot class="location-tfoot">
                            <tr class="edit_del_location">
                                <td>
                                    <a
                                        href="{% url 'landingpage:update_location' address.pk %}">Update</a>
                                </td>

                                <td>
                                    <a
                                        href="{% url 'landingpage:delete_location' address.pk %}">Delete</a>
                                </td>
                            </tr>
                        </tfoot>

                    </table>

                    
                </div>
            </div>
            {% endfor %}

            {% else %}
            <h1 class="empty">Empty</h1>
            {% endif %}
        </section>


        <section class="footer" id="social">

            <div class="foot-user">
                <h1 id="footer-links">Links</h1>
                {% if links %}
                <table class="links-table">
                    <tbody class="links-tbody">
                        {% for s in links %}
                        {% ifchanged s.name%}
                        <tr>
                            <th>{{ s.name.name }}</th>
                            <td class="edit_del_social">
                                <a href="{% url 'landingpage:update_social' s.name.pk %}">Update</a>
                                <a href="{% url 'landingpage:delete_social' s.name.pk %}">Delete</a>
                            </td>
                        </tr>
                        {% endifchanged %}
                        <tr>
                            <td colspan="2">{{ s.links|truncatechars:30 }}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                

                {% else %}
                <h1 class="emp">Empty</h1>
                {% endif %}
            </div>

        </section>

        <a href="#header" id="up">&uharl;
        </a>
    </div>
</body>

</html>