blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostsView.as_view(), name='posts'),
    path('post/<slug:post_slug>/', views.detail_post, name='detail_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/<slug:post_slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('categories_list/', views.categories_list, name='categories_list'),
    path('by_category/<slug:category_slug>/', views.ByCategory.as_view(), name='by_category'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('search/', views.SearchView.as_view(), name='search_list'),
    path('like/<slug:slug>/', views.like_post, name='like_post'),
    path('about/', views.AboutView.as_view(), name='about'),
    
    path('user_posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path('user_detail_post/<slug:post_slug>/', views.user_detail_post, name='user_detail_post'),
    path('delete_comment/<int:pk>/', views.delete_commet, name='delete_comment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('thereisno_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('mainapp.urls')),
    path('account/', include('registration.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('landing_page/', include('landingpage.urls')),
    path('gallery/', include('gallery.urls')),

]

handler404 = 'mainapp.views.my_error404'
handler403 = 'mainapp.views.my_error403'
handler500 = 'mainapp.views.my_error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('registration/done/', views.RegistrationDoneView.as_view(), name='registration_done'),
    path('registration/activate/<str:sign>/', views.user_activeted, name='user_activated'),


    path('profile/<int:pk>/', views.ProfileView, name='profile'),
    path('cahge_info/<int:pk>/', views.UpdateProfile, name='change_info'),
    path('delete_user/', views.DeleteUserView.as_view(), name='delete_user'),
    path('delete_user_done/', views.DeleteUserDone.as_view(), name='delete_user_done'),


    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('logout_view/', views.logout_view, name='logout_view'),

    path('change_password/', views.change_password, name='change_password'),
    path('change_password_done/', views.ChangePasswordDone.as_view(), name='change_password_done'),

    path('reset_password/', views.ResetPassView.as_view(), name='reset_password'),
    path('reset_password_done/', views.ResetPassViewDone.as_view(), name='reset_password_done'),
    path('reset_password_confirm/<uidb64>/<token>/', views.ResetPassViewConfirm.as_view(), name='reset_password_confirm'),
    path('reset_password_complete/', views.ResetPassViewComplete.as_view(), name='reset_password_complete'),
]

blog/models.py
from django.db import models, migrations
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django_resized import ResizedImageField
from easy_thumbnails.fields import ThumbnailerImageField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.



# Validate image in extra images -----------------------------------------------------------
def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit*1024*1024:
        raise ValidationError("Max image size is %sMB" % str(megabyte_limit))


# Validate vidoe in post -----------------------------------------------------------
def validate_video(video_obj):
    videisize = video_obj.file.size
    megabyte_limit = 50.0
    if videisize > megabyte_limit * 1024 * 1024:
        raise ValidationError('Max video size is %sMB' % str(megabyte_limit))


# Ip for count views -----------------------------------------------------------
class IpModel(models.Model):
    ip = models.CharField(max_length=100, blank=True, null=True)
    post = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.ip, self.post)


# Category ------------------------------------------------------------------------
class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='blog/category/image/')
    slug = models.SlugField(max_length=50, unique=True, help_text='Slug must be the same as Name! Use only "-" insted space" " and the others')

    def __str__(self):
        return self.name


# Post ----------------------------------------------------------------------------
class Post(models.Model):
    title = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, help_text='Slug must be the same as Name! Use only "-" insted space" " and the others')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    short_description = RichTextUploadingField(config_name='base')
    text = RichTextUploadingField()
    video = models.FileField(upload_to='blog/post/vidoe/%Y/%m/%d/', null=True, blank=True, validators=[validate_video], help_text='Max video size is 50 MB!')
    thumbnail = ThumbnailerImageField(resize_source={'size': (800, 0), 'crop': 'scale', 'quality': 80}, upload_to='blog/thumbnail/%Y/%m/%d/')
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    show = models.BooleanField(default=True, db_index=True)
    likes = models.ManyToManyField(User, related_name='blog_post', blank=True, null=True, default=0)
    views = models.PositiveIntegerField(default=0, blank=True, null=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    # Remove extra images when delete post ------------------------------------
    def delete(self, *args, **kwargs):
        for ei in self.extraimage_set.all():
            ei.delete()
        super().delete(*args, **kwargs)
    
    class Meta:
        ordering = ['-created']

# extra images for post-----------------------------------------------------------------
class ExtraImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = ThumbnailerImageField(resize_source={'size': (800, 0), 'crop': 'scale', 'quality': 80},upload_to='blog/post/image/%Y/%m/%d/', blank=True, null=True, validators=[validate_image], help_text='Maximum image size allowed is 2Mb')


# Social name -----------------------------------------------------------------------
class SocialName(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self) -> str:
        return self.name


# Links for Social name ----------------------------------------------------------------
class Links(models.Model):
    name = models.ForeignKey(SocialName, on_delete=models.CASCADE)
    links = models.URLField(blank=True, null=True)


# Comment for post ------------------------------------------------------------------------
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default='anonim')
    text = RichTextUploadingField(config_name='simple')
    created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return '%s - %s' % (self.name, self.post)

    class Meta:
        ordering = ['-created']


# About --------------------------------------------------------------
class About(models.Model):
    description = RichTextUploadingField()
    image = models.ImageField(upload_to='blog/about/image/', validators=[validate_image], help_text='Maximum image size allowed is 2Mb')
    video = models.FileField(upload_to='blog/about/video/', validators=[validate_video], help_text='Maximum video size is 50 MB!')
    active = models.BooleanField(default=False)

blog/forms.py
from django import forms
from captcha.fields import CaptchaField
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Post, ExtraImage, Category, Comment


# Create Post form ------------------------------------------------------------------------
class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('likes', 'views')
        widgets = {
            'author': forms.HiddenInput,
            'text': CKEditorUploadingWidget(),
            'short_description': CKEditorUploadingWidget(),
        }


# extra images for Post form ------------------------------------------------------------------------
ExtraImageForm = forms.inlineformset_factory(Post, ExtraImage, fields='__all__', extra=5, can_delete_extra=False)


# Search form ------------------------------------------------------------------------
class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=50)


# Create category form ------------------------------------------------------------------------
CreateCategoryForm = forms.modelformset_factory(Category, fields='__all__', can_delete=False, extra=5)


# user comment form -------------------------------------------------------------------
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {
            'post': forms.HiddenInput,
            'text': CKEditorUploadingWidget(),
        }


# guest comment form -------------------------------------------------------------------
class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {
            'post': forms.HiddenInput,
            'text': CKEditorUploadingWidget(),

        }

blog/templates/blog/about.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} Blog::About {% endblock title %}

{% block csslink %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock csslink %}

{% block content %}
<h2>About me</h2>
<div class="posts">
    {% if about %}
    <div class="post">

        <img src="{{ about.image.url }}" alt="image">
        <p>{{ about.description }}</p>

        <video controls>
            <source type="video/mp4" src="{{ about.video.url }}">
        </video>

        <ul>
            <h2>follow me:</h2>
            {% for link in sociallinks %}

            <li>{{ link.name }}</li>

            {% for l in link.links_set.all %}
            <a href="{{ l.links }}">{{ l.links }}</a><br>
            {% endfor %}
            <br>
            {% endfor %}
        </ul>
        <a href="{% url 'blog:posts' %}" class="readmore">back</a>
    </div>

    {% else %}
    <h2>There is not information About us yet</h2>
    {% endif %}
</div>


{% endblock content %}

blog/templates/blog/blog.html
{% extends 'layout/base.html' %}
{% load thumbnail %}
{% block title %} Blog {% endblock title %}
{% block content %}
<h2>All posts</h2>
{% if posts %}

<div class="posts">
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'blog:detail_post' post.slug %}" class="aimg"><img
                src="{{ post.thumbnail.url }}" alt="image"></a>
        <h3>{{ post.title }}</h3>

        <div class="paragraph">{{ post.short_description|safe }}</div>

        <a href="{% url 'blog:detail_post' post.slug %}" class="readmore">readmore</a>
        <aside>views: {{ post.views }}</aside>
        <aside>added: {{ post.created }}</aside>
    </div>
    {% endfor %}

</div>
{% else %}
<h2>We have not added post yet</h2>
{% endif %}

{% if page_obj.has_other_pages %}
<div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        {% endif %}

        <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>

        {% endif %}
</div>
{% endif %}

{% endblock content %}

blog/templates/blog/by_category.html
{% extends 'layout/base.html' %}

{% block title %} Blog::By category {% endblock title %}

{% block content %}
<h2>{{ current_category }}</h2>

<div class="posts">
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'blog:detail_post' post.slug %}{{ all }}" class="aimg"><img src="{{ post.thumbnail.url }}" alt="image"></a>
        <h3>{{ post.title }}</h3>
        <div class="paragraph">{{ post.short_description|safe }}</div>
        <a href="{% url 'blog:detail_post' post.slug %}{{ all }}" class="readmore">readmore</a>
        <aside>views</aside>
        <aside>added</aside>
    </div>
    {% endfor %}
</div>
{% if page_obj.has_other_pages %}
<div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        {% endif %}

        <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>

        {% endif %}
</div>
{% endif %}
{% endblock content %}

blog/templates/blog/categories.html
{% extends 'layout/base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %} Blog::Categories {% endblock title %}

{% block csslink %}
<link rel="stylesheet" href="{% static 'css/categories.css' %}">
{% endblock csslink %}


{% block content %}
<h2>Categories</h2>
{% if categories %}

<div class="posts">
    {% for cat in categories %}
    <div class="post">
        <a href="{% url 'blog:by_category' cat.slug %}" class="aimg"><img src="{% thumbnail cat.image 'cat_img' %}" alt="image"></a>
        <a href="{% url 'blog:by_category' cat.slug %}" class="readmore">{{ cat.name }}</a>
    </div>
    {% endfor %}
 
</div>
{% else %}
<h2>There are no categories</h2>
{% endif %}
{% endblock content %}

blog/templates/blog/create_category.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} Blog::Create/update category {% endblock title %}


{% block csslink %}
<link rel="stylesheet" href="{% static 'css/create_cat.css' %}">
{% endblock csslink %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="message">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>
{% endfor %}
{% endif %}

<h2>Create new / update categories</h2>
<div class="create">
    <div class="post">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            
            <input type="submit" id="createpost" value="create category">
        </form>
    </div>

</div>
{% endblock content %}

blog/templates/blog/create_post.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} Blog::Create/update post {% endblock title %}


{% block csslink %}
<link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock csslink %}



{% block content %}

{% if messages %}
{% for message in messages %}
<div class="message">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>
{% endfor %}
{% endif %}

<h2>{{ save }} post {% if post %}"{{ post.title }}"{% endif %}</h2>
<div class="create">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form }}
        <h2>Extra images</h2>
        {{ formset }}
        <input type="submit" id="createpost" value="{{save}} post">
    </form>
</div>
{% endblock content %}

blog/templates/blog/delete_post.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %} Blog::Delete post {% endblock title %}


{% block csslink %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock csslink %}

{% block content %}

<h2>Delete page</h2>
<div class="posts">
    <div class="post">
        <h2>{{ post.title }}</h2>

        <img class="thumbnail" src="{{ post.thumbnail.url }}" alt="image">
        <div class="paragraph">{{ post.text|safe }}</div>

        {% if eis %}
        <h3>images</h3>
        <div class="images">
            {% for ei in eis %}
            <img src="{{ ei.image.url }}" alt="image">
            {% endfor %}
        </div>
        {% endif %}

        {% if post.video %}
        <h3>video</h3>
        <video controls>
            <source type="video/mp4" src="{{ post.video.url }}">
        </video>
        {% endif %}

        <aside>Author: {{ post.author }}</aside>
        <aside>Category: {{ post.category }}</aside>
        <aside>views: {{ post.views }}</aside>
        <aside>likes: {{ post.total_likes }}</aside>
        <aside>comments: {{ post.comment_set.count }}</aside>
        <aside>added: {{ post.created }}</aside>
        <aside>changed: {{ post.changed }}</aside>
      <form class="likes" action="" method="post">
        {% csrf_token %}
        <input class="unlike" type="submit" id="readmore" value="Delete post">
      </form>
        <a href="{% url 'blog:user_detail_post' post.slug %}" class="readmore">back</a>
    </div>
</div>


{% endblock content %}

blog/templates/blog/delete_user_comment.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %} Blog::Delete comment {% endblock title %}



{% block csslink %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock csslink %}

{% block content %}
<h2>Delete comment from post "{{ comment.post }}"</h2>

<div class="comments">
    <h2>Comment</h2>
    <div class="com">
        <aside>{{ comment.name }} | {{ comment.created }}
        </aside>
        <div class="comment-text">{{ comment.text|safe }}</div>

    </div>

    <form action="{% url 'blog:delete_comment' comment.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="delete">
    </form>
    <a href="{% url 'blog:user_detail_post' comment.post.slug %}" class="readmore">back</a>

</div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %} Blog::Post:{{ post.title }} {% endblock title %}


{% block csslink %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock csslink %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="message">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
</div>
{% endfor %}
{% endif %}

<h2>Detail view</h2>
<div class="posts">
    <div class="post">
        <h2>{{ post.title }}</h2>


        <img class="thumbnail" src="{{ post.thumbnail.url }}" alt="image">
        <div class="paragraph">{{ post.text|safe }}</div>

        {% if eis %}
        <h2>images</h2>
        <div class="images">
            {% for ei in eis %}
            <img src="{{ ei.image.url }}" alt="image">
            {% endfor %}
        </div>
        {% endif %}

        {% if post.video %}
        <h2>video</h2>
        <video controls>
            <source type="video/mp4" src="{{ post.video.url }}">
        </video>
        {% endif %}

        <aside>Author: {{ post.author }}</aside>
        <aside>Category: {{ post.category }}</aside>
        <aside>views: {{post.views}} &#128065;</aside>
        <aside>added: {{ post.created }}</aside>
        <aside>changed: {{ post.changed }}</aside>

        <form class="likes" action="{% url 'blog:like_post' post.slug %}" method="post">
            {% csrf_token %}
            {% if user.is_authenticated %}
            {% if liked %}
            <input class="unlike" type="submit" value="UnLike">
            {% else %}
            <input class="like" type="submit" value="Like">
            {% endif %}
            {% else %}
            <a href="{% url 'registration:login' %}">Login to like</a>
            {% endif %}
            <aside>{{ total_likes }} likes</aside>

        </form>
        <a href="{% if keyword %}{% url 'blog:search_list' %}{{ all }}{% else %}{% url 'blog:by_category' post.category.slug %}{{ all }}{% endif %}" class="readmore">back</a>
    </div>
</div>
<div class="comments">
    <h2>Comments</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form }}
        <input type="submit" value="Add comment">
    </form>
    {% for comment in comments %}
    <div class="com">
        <aside>{{ comment.name }} | {{ comment.created }}</aside>
        <div class="comment-text">{{ comment.text|safe }}</div>
    </div>
    {% endfor %}


</div>
{% endblock content %}

blog/templates/blog/detail_user_post.html
{% extends 'layout/base.html' %}
{% load static %}


{% block title %} Blog::{{ request.user.username}}'s post:{{post.title}}{% endblock title %}


{% block csslink %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock csslink %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="message">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
</div>
{% endfor %}
{% endif %}
<h2>Detail view</h2>
<div class="posts">
    <div class="post">
        <div class="edit">
            <a href="{% url 'blog:update_post' post.slug %}" class="update">update</a>
            <a href="{% url 'blog:delete_post' post.slug %}" class="delete">delete</a>
        </div>

        <h2>{{ post.title }}</h2>


        <img class="thumbnail" src="{{ post.thumbnail.url }}" alt="image">

        <div class="paragraph">{{ post.text|safe }}</div>

        {% if eis %}
        <h2>images</h2>
        <div class="images">
            {% for ei in eis %}
            <img src="{{ ei.image.url }}" alt="image">
            {% endfor %}
        </div>
        {% endif %}

        {% if post.video %}
        <h2>video</h2>
        <video controls>
            <source type="video/mp4" src="{{ post.video.url }}">
        </video>
        {% endif %}

        <aside class="">Author: {{ post.author }}</aside>
        <aside class="">Category: {{ post.category }}</aside>
        <aside class="">views: {{post.views}} &#128065;</aside>
        <aside class="">added: {{ post.created }}</aside>
        <aside class="">changed: {{ post.changed }}</aside>

        <a href="{% url 'blog:user_posts' user.pk %}{{ all }}" class="readmore">back</a>
    </div>
</div>
<div class="comments">
    <h2>Comments</h2>
    {% for comment in comments %}
    <div class="com">
        <aside>{{ comment.name }} | {{ comment.created }}</aside>
        <div class="comment-text">{{ comment.text|safe }}</div>
        <a href="{% url 'blog:delete_comment' comment.pk %}" class="del">delete</a>

    </div>
    {% endfor %}


</div>
{% endblock content %}

blog/templates/blog/search_list.html
{% extends 'layout/base.html' %}


{% block title %} Blog::Search:{{ keyword }} {% endblock title %}


{% block content %}
<h2>Search: {{ keyword }}</h2>
{% if posts %}

<div class="posts">
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'blog:detail_post' post.slug %}{{ all }}" class="aimg"><img
                src="{{ post.thumbnail.url }}" alt="image"></a>
        <h3>{{ post.title }}</h3>
        <div class="paragraph">{{ post.short_description|safe }}</div>
        <a href="{% url 'blog:detail_post' post.slug %}{{ all }}" class="readmore">read more</a>
        <aside>views: {{ post.views }}</aside>
        <aside>added: {{ post.created }}</aside>
    </div>
    {% endfor %}

</div>
{% else %}
<h2>Nothing</h2>
{% endif %}

{% if page_obj.has_other_pages %}
<div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?{% if keyword %}q={{keyword}}&{% endif %}page=1">First</a>
        <a href="?{% if keyword %}q={{keyword}}&{% endif %}page={{ page_obj.previous_page_number }}">&lt;</a>
        {% endif %}

        <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>

        {% if page_obj.has_next %}
        <a href="?{% if keyword %}q={{keyword}}&{% endif %}page={{ page_obj.next_page_number }}">&gt;</a>
        <a href="?{% if keyword %}q={{keyword}}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last</a>

        {% endif %}
</div>
{% endif %}

{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'layout/base.html' %}
{% load thumbnail %}


{% block title %} Blog::{{ request.user.username }}'s posts {% endblock title %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="message">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
</div>
{% endfor %}
{% endif %}

<h2>{{ user.username }}'s posts</h2>
{% if posts %}

<div class="posts">
    {% for post in posts %}
    <div class="post">
        <a href="{% url 'blog:user_detail_post' post.slug %}{{ all }}" class="aimg"><img
                src="{{ post.thumbnail.url }}" alt="image"></a>
        <h3>{{ post.title }}</h3>
        <div class="paragraph">{{ post.short_description|safe }}</div>


        <a href="{% url 'blog:user_detail_post' post.slug %}{{ all }}" class="readmore">readmore</a>
        <aside>views: {{ post.views }}</aside>
        <aside>added: {{ post.created }}</aside>
    </div>
    {% endfor %}

</div>
{% else %}
<h2>You have not written post yet</h2>
{% endif %}

{% if page_obj.has_other_pages %}
<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page=1">First</a>
    <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
    {% endif %}

    <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>

    {% endif %}
</div>
{% endif %}

{% endblock content %}