blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostsView.as_view(), name='posts'),
    path('post/<slug:post_slug>/', views.detail_post, name='detail_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/<slug:post_slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('categories_list/', views.categories_list, name='categories_list'),
    path('by_category/<slug:category_slug>/', views.ByCategory.as_view(), name='by_category'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('search/', views.SearchView.as_view(), name='search_list'),
    path('like/<slug:slug>/', views.like_post, name='like_post'),
    path('about/', views.AboutView.as_view(), name='about'),
    
    path('user_posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path('user_detail_post/<slug:post_slug>/', views.user_detail_post, name='user_detail_post'),
    path('delete_comment/<int:pk>/', views.delete_commet, name='delete_comment'),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.check)

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('thereisno_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('mainapp.urls')),
    path('account/', include('registration.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('landing_page/', include('landingpage.urls')),
    path('gallery/', include('gallery.urls')),

]

handler404 = 'mainapp.views.my_error404'
handler403 = 'mainapp.views.my_error403'
handler500 = 'mainapp.views.my_error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('registration/done/', views.RegistrationDoneView.as_view(), name='registration_done'),
    path('registration/activate/<str:sign>/', views.user_activeted, name='user_activated'),


    path('profile/<int:pk>/', views.ProfileView, name='profile'),
    path('cahge_info/<int:pk>/', views.UpdateProfile, name='change_info'),
    path('delete_user/', views.DeleteUserView.as_view(), name='delete_user'),
    path('delete_user_done/', views.DeleteUserDone.as_view(), name='delete_user_done'),


    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('logout_view/', views.logout_view, name='logout_view'),

    path('change_password/', views.change_password, name='change_password'),
    path('change_password_done/', views.ChangePasswordDone.as_view(), name='change_password_done'),

    path('reset_password/', views.ResetPassView.as_view(), name='reset_password'),
    path('reset_password_done/', views.ResetPassViewDone.as_view(), name='reset_password_done'),
    path('reset_password_confirm/<uidb64>/<token>/', views.ResetPassViewConfirm.as_view(), name='reset_password_confirm'),
    path('reset_password_complete/', views.ResetPassViewComplete.as_view(), name='reset_password_complete'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('cart/cart_detail/', views.cart_detail, name='cart_detail'),
    path('cart/add_cart/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart/remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    
    path('', views.shop, name='shop'),
    path('all_products/', views.ProductView.as_view(), name='products'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('category/<int:pk>/', views.sub_categories, name='sub_categories'),
    path('sub_category/<int:pk>/', views.by_category, name='by_category'),
    path('cart_order/', views.CartOrder.as_view(), name='cart_order'),
    path('order_list/', views.OrderView.as_view(), name='order_list'),
    path('search/', views.Search.as_view(), name='search'),
    path('add_product/', views.add_product, name='add_product'),
    path('author_product/<int:pk>/', views.author_product, name='author_product'),
    path('the_most_viewed_products/', views.viewed_product, name='viewed_product'),
    path('the_most_viewed_categories/', views.viewed_category, name='viewed_category'),
    path('filter_product/', views.filter_product, name='filter_product'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('user_products/<int:pk>/', views.UserProductsView.as_view(), name='user_products'),
    path('user_detail_product/<int:pk>/', views.UserDetailProductView.as_view(), name='user_detail_product'),
    path('user_update_product/<int:pk>/', views.update_user_product, name='user_update_product'),
    path('user_delete_product/<int:pk>/', views.DelUserProductView.as_view(), name='user_delete_product'),

]

shop/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Product, ExtraImage, SubCategory


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control'}), label='Qnt:', min_value=0)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)


# Add Product form ----------------------------------------------------------------
class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('views',)
        widgets = {
            'author': forms.HiddenInput,
            'desctiption': CKEditorUploadingWidget(),
            'info': CKEditorUploadingWidget(),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'slug': forms.TextInput(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'thumbnail': forms.FileInput(attrs={'class':'form-control'}),
            'price': forms.NumberInput(attrs={'class':'form-control'}),
        }


# Extra images form for product form --------------------------------------------------
ExtraImageForm = forms.inlineformset_factory(Product, ExtraImage, fields='__all__', extra=5, can_delete_extra=False, widgets={
    'image': forms.FileInput(attrs={'class': 'form-control'})
    })

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
from .models import ExtraImage, Order, Product, SubCategory, SuperCategory, IpModel, IpCategory, About, Carousel
from .forms import CartAddForm, AddProductForm, ExtraImageForm
from .cart import Cart


# fist shop page -------------------------------------------
def shop(request):
    about = About.objects.get(show=True)
    carousel = about.carousel_set.all()
    products = Product.objects.order_by('-created_at')[:6]
    products_viewed = Product.objects.order_by('-views')[:4]
    cats_viewed = SubCategory.objects.order_by('-views')[:6]
    context = {'products': products,
               'products_viewed': products_viewed, 'cats_viewed': cats_viewed, 'about':about, 'carousel':carousel}
    return render(request, 'shop/shop.html', context)


# list products --------------------------------
class ProductView(ListView):
    paginate_by = 8
    model = Product
    template_name = 'shop/shop_products.html'
    context_object_name = 'products'

# product detail --------------------------------


def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    same_products = Product.objects.filter(name__icontains=product.name.split()[0])[:6]
    product_name = product.name.split()[0]
    author_products = Product.objects.filter(author=product.author)[:6]
    eis = product.extraimage_set.all()
    cart_form = CartAddForm()

    ip = get_ip(request)
    s = slug
    results = IpModel.objects.filter(ip=ip, product=s)
    if results.exists():
        print(results)
    else:
        IpModel.objects.create(ip=ip, product=s)
        product.views = product.views + 1
        product.save()
        print('user is unique', results)

    context = {'product': product, 'eis': eis, 'cart_form': cart_form,
               'same_products': same_products, 'p': product_name, 'author_products': author_products}
    return render(request, 'shop/shop_detail.html', context)


# categories page -------------------------------------
class CategoriesView(ListView):
    model = SuperCategory
    template_name = 'shop/shop_categories.html'
    context_object_name = 'cats'


# Subcategories page -------------------------------------
def sub_categories(request, pk):
    current_super_category = SuperCategory.objects.get(pk=pk)
    sub_categories = SubCategory.objects.filter(sup_category=pk)
    context = {'current_super_category': current_super_category,
               'sub_categories': sub_categories}
    return render(request, 'shop/shop_sub_categories.html', context)


# by_subcategories page -------------------------------------
def by_category(request, pk):
    products = Product.objects.filter(category=pk)
    current_cat = SubCategory.objects.get(pk=pk)
    paginator = Paginator(products, 8)

    if 'page' in request.GET:
        page_num = request.GET.get('page')
    else:
        page_num = 1
    page_obj = paginator.get_page(page_num)

    ip = get_ip(request)
    s = pk
    results = IpCategory.objects.filter(ip=ip, sub_categories=s)
    if results.exists():
        print(results)
    else:
        IpCategory.objects.create(ip=ip, sub_categories=s)
        current_cat.views = current_cat.views + 1
        current_cat.save()
        print('user is unique', results)

    context = {'products': page_obj.object_list,
               'current_cat': current_cat, 'page_obj': page_obj}
    return render(request, 'shop/shop_by_category.html', context)


# add cart ----------------------------------------------
@require_POST
def add_cart(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('shop:cart_detail')


def remove_cart(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    cart.remove(product)
    messages.success(request, 'Product has removed')
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['form'] = CartAddForm(
            initial={'quantity': item['quantity'], 'update': True})
    context = {'cart': cart}
    return render(request, 'shop/shop_cart.html', context)
# end card ------------------------------------------------


# Get user ip --------------------------------------------------------------------------
def get_ip(request):
    address = request.META.get('HTTP_X_FORWARDED_FOR')
    if address:
        ip = address.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


# Check out ------------------------------------------------------
class CartOrder(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        cart = request.session.get('cart')
        products = Product.objects.filter(pk__in=list(cart.keys()))
        for product in products:
            order = Order(
                product=Product.objects.get(pk=product.pk),
                customer=product.author,
                price=product.price,
                address=address,
                phone=phone,
                quantity=cart[str(product.id)]['quantity'],
            )
            order.place_order()
            request.session['cart'] = dict()
        messages.success(request, 'Your order has sent.')
        return redirect('shop:order_list')


# Order page ----------------------------------------
class OrderView(View):
    def get(self, request):
        customer = request.user.id
        orders = Order.customer_orders(customer)
        qs = []
        qp = []
        for s in orders:
            qs.append(s.quantity)
            q = s.quantity
            p = s.price
            qp.append(q*p)
        qs = sum(qs)
        qp = sum(qp)
        context = {'orders': orders, 'total_q': qs, 'total_p': qp}
        return render(request, 'shop/shop_order.html', context)


# shear list ---------------------------------------------------------
class Search(View):
    def get(self, request):
        keyword = request.GET.get('search')
        products = Product.objects.filter(name__icontains=keyword)
        paginator = Paginator(products, 4)
        if 'page' in request.GET:
            page_num = request.GET.get('page')
        else:
            page_num = 1
        page_obj = paginator.get_page(page_num)
        context = {'keyword': keyword,
                   'products': page_obj.object_list, 'page_obj': page_obj}
        return render(request, 'shop/shop_search_list.html', context)


# Add Product Form ----------------------------------------------
def add_product(request):
    form = AddProductForm()
    formset = ExtraImageForm()
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            formset = ExtraImageForm(
                request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
                messages.success(
                    request, 'The product has added successfully!')
                return redirect('shop:add_product')
        else:
            messages.warning(request, 'The product has not added try again!')

    else:
        form = AddProductForm(initial={'author': request.user.pk})
        formset = ExtraImageForm()
    context = {'form': form, 'formset': formset}
    return render(request, 'shop/shop_add_product.html', context)


# products by author-------------------------------------------------------------
def author_product(request, pk):
    products = Product.objects.filter(author=pk)
    paginator = Paginator(products, 4)
    if 'page' in request.GET:
        page_num = request.GET.get('page')
    else:
        page_num = 1
    page_obj = paginator.get_page(page_num)
    context = {'products': page_obj.object_list, 'page_obj': page_obj}
    return render(request, 'shop/author_products.html', context)


# user products --------------------------------------------------
class UserProductsView(ListView):
    paginate_by = 8
    template_name = 'shop/shop_user.html'
    context_object_name = 'products'

    def get_queryset(self):
        products = Product.objects.filter(author=self.request.user.pk)
        return products

# user detail product --------------------------------------------------
class UserDetailProductView(DetailView):
    template_name = 'shop/shop_user_detail_product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = DetailView.get_context_data(self, **kwargs)
        eis = self.product.extraimage_set.all()
        context['eis'] = eis
        return context

    def setup(self, request, *args, **kwargs):
        self.pk = kwargs['pk']
        return super().setup(request, *args, **kwargs)

    def get_object(self):
        self.product = Product.objects.get(pk=self.pk)
        return self.product


# update user product --------------------------------------------------
def update_user_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            formset = ExtraImageForm(

shop/templates/inc/_footer.html
<!-- footer --------------------------------------- -->

<footer class="container-fluid border-top bg-light mt-5 pb-5">
    <div class="container text-center">
        <div class="row text-center pt-5 pb-5">
            <div class="col-lg-2 col-sm-6">
                <h5 class="text-primary">Menu</h5>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'mainapp:index' %}" class="nav-link">Main page</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'shop:shop' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'shop:categories' %}" class="nav-link">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'shop:about' %}" class="nav-link">About</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-sm-6">
                <h5 class="text-primary">Buy</h5>
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'shop:cart_detail' %}"
                            class="nav-link">Cart</a></li>
                    <li class="nav-item"><a href="{% url 'shop:order_list' %}"
                            class="nav-link">Order</a></li>
                </ul>
            </div>
            <div class="col-lg-4 col-sm-6">
                <h5 class="text-primary">Contacts</h5>
                {% if contact %}
                {% for c in contact %}
                <address class="text-start">
                    <h5>{{ c.name }}</h6>
                    Address 1: {{ c.address1 }},
                    <br>
                    <br>
                    Address 2: {{ c.address2 }},
                    <br>
                    <br>
                    <h6>Phone: {{ c.phone }}</h6>
                </address>
                {% endfor %}
                {% else %}
                <h3 class="text-secondary">empty</h3>
                {% endif %}
            </div>
            <div class="col-lg-4 col-sm-6">
                <h5 class="text-primary">Search</h5>
                <form action="{% url 'shop:search' %}" class="col-lg-12 justify-content-center">
                    <input type="search" class="form-control me-3" name="search">
                    <button class="btn btn-outline-primary mt-3 w-100" type="submit">Search</button>
                </form>
            </div>
        </div>

        <small>&copy; {% now "Y" %} Lorem ipsum dolor sit amet.</small>
    </div>
    
</footer>
<!-- end footer --------------------------------------- -->

shop/templates/inc/filter.html
<div class="col-lg-3 border-end mb-3">
    <h5 class="fs-3">Filter</h5>
    <aside><small>Choose only one filter</small></aside>

    <form action="{% url 'shop:filter_product' %}" method="get" class="fs-5">
        <div class="form-check my-3">
            <label for="high_p" class="form-check-label">High price</label>
            <input type="checkbox" name="high_price" id="high_p" class="form-check-input">
        </div>

        <div class="form-check my-3">
            <label for="low_p" class="form-check-label">Low price</label>
            <input type="checkbox" name="low_price" id="low_p" class="form-check-input">
        </div>

        <div class="form-check my-3">
            <label for="new_p" class="form-check-label">New product</label>
            <input type="checkbox" name="new" id="new_p" class="form-check-input" checked>
        </div>

        <div class="form-check my-3">
            <label for="viewed_p" class="form-check-label">Viewed</label>
            <input type="checkbox" name="viewed" id="viewed_p" class="form-check-input">
        </div>
        <input type="submit" value="filter" class="btn btn-primary w-100">

    </form>
</div>

shop/templates/inc/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example" class="mt-3">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{% if keyword %}search={{ keyword }}&{% elif viewed %}viewed=on&{% elif low_price %}low_price=on&{% elif high_price %}high_price=on&{% elif new %}new=on&{% endif %}page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-item">
            <a class="page-link active" href="">{{ p }}</a>
        </li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %} <li class="page-item">
            <a class="page-link" href="?{% if keyword %}search={{ keyword }}&{% elif viewed %}viewed=on&{% elif low_price %}low_price=on&{% elif high_price %}high_price=on&{% elif new %}new=on&{% endif %}page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% if keyword %}search={{ keyword }}&{% elif viewed %}viewed=on&{% elif low_price %}low_price=on&{% elif high_price %}high_price=on&{% elif new %}new=on&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% endif %}
    </ul>
</nav>
{% endif %}

shop/templates/inc/shop_header.html
<!-- header / navbar --------------------------------------- -->
<div class="container-fluid bg-light">
    <div class="container-fluid border-bottom">
        <div class="container">
            {% if not user.is_authenticated %}

            <div class="row py-1 justify-content-start mt-1">
                <a href="{% url 'registration:login' %}"
                    class="btn btn-outline-primary btn-sm col-md-2 col-4 me-3"><i
                        class="bi bi-pencil"></i></i> Log in</a>
                <a href="{% url 'registration:registration' %}"
                    class="btn btn-outline-primary btn-sm col-md-2 col-4"><i
                        class="bi bi-person-plus-fill"></i></i>
                    Sign up</a>
            </div>
            {% else %}
            <div class="row py-1 justify-content-start mt-1">
                <a href="{% url 'registration:logout' %}"
                    class="btn btn-primary btn-sm col-md-2 col-4 me-3"><i class="bi bi-person-dash-fill"></i>Logout: {{ user.username }}</a>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="container border-bottom">
        <div class="row navbar justify-content-between">

            <a href="{% url 'shop:shop' %}" class="navbar-brand col-md-2 col-12 my-1 btn btn-outline-primary">Shop</a>

            <form action="{% url 'shop:search' %}" class="col-md-7 d-flex col-12 my-1 p-0">
                <input type="search" class="form-control me-3" name="search">
                <button class="btn btn-primary " type="submit">Search</button>
            </form>


            <a href="{% url 'shop:cart_detail' %}"
                class="btn btn-outline-primary col-md-1 col-5 mt-1">
                <i class="bi bi-cart3 fs-5"></i>
                {% if cart.total_items > 0 %}
                <span class="badge bg-primary">{{ cart.total_items }}</span>
                {% else %}
                <span>Cart</span>
                {% endif %}
            </a>
            <a href="{% url 'shop:order_list' %}"
                class="btn btn-outline-primary col-md-1 col-5 mt-1">
                <i class="bi bi-cart3 fs-5"></i>
                Order
            </a>
        </div>
    </div>
</div>


<nav class="navbar navbar-expand-md bg-light border-bottom">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'mainapp:index' %}" class="nav-link">Main page</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:shop' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:categories' %}" class="nav-link">Categories</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:about' %}" class="nav-link">About</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'shop:user_products' user.pk %}" class="nav-link">Your products</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:add_product' %}" class="nav-link">Add product</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'mainapp:index' %}" class="nav-link">Login or registration to add product</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<div class="container-fluid border-bottom pt-3 ">
    {% if breadcrumbs %}
    <div class="container">
        {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs %}
    </div>
    {% endif %}

</div>


<!-- end navbar --------------------------------------- -->