blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostsView.as_view(), name='posts'),
    path('post/<slug:post_slug>/', views.detail_post, name='detail_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('update_post/<slug:post_slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:post_slug>/', views.DeletePostView.as_view(), name='delete_post'),
    path('categories_list/', views.categories_list, name='categories_list'),
    path('by_category/<slug:category_slug>/', views.ByCategory.as_view(), name='by_category'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('search/', views.SearchView.as_view(), name='search_list'),
    path('like/<slug:slug>/', views.like_post, name='like_post'),
    path('about/', views.AboutView.as_view(), name='about'),
    
    path('user_posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path('user_detail_post/<slug:post_slug>/', views.user_detail_post, name='user_detail_post'),
    path('delete_comment/<int:pk>/', views.delete_commet, name='delete_comment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('thereisno_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('mainapp.urls')),
    path('account/', include('registration.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('landing_page/', include('landingpage.urls')),
    path('gallery/', include('gallery.urls')),

]

handler404 = 'mainapp.views.my_error404'
handler403 = 'mainapp.views.my_error403'
handler500 = 'mainapp.views.my_error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('cart/cart_detail/', views.cart_detail, name='cart_detail'),
    path('cart/add_cart/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart/remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    
    path('', views.shop, name='shop'),
    path('all_products/', views.ProductView.as_view(), name='products'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('category/<int:pk>/', views.sub_categories, name='sub_categories'),
    path('sub_category/<int:pk>/', views.by_category, name='by_category'),
    path('cart_order/', views.CartOrder.as_view(), name='cart_order'),
    path('order_list/', views.OrderView.as_view(), name='order_list'),
    path('search/', views.Search.as_view(), name='search'),
    path('add_product/', views.add_product, name='add_product'),
    path('author_product/<int:pk>/', views.author_product, name='author_product'),
    path('the_most_viewed_products/', views.viewed_product, name='viewed_product'),
    path('the_most_viewed_categories/', views.viewed_category, name='viewed_category'),
    path('filter_product/', views.filter_product, name='filter_product'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('user_products/<int:pk>/', views.UserProductsView.as_view(), name='user_products'),
    path('user_detail_product/<int:pk>/', views.UserDetailProductView.as_view(), name='user_detail_product'),
    path('user_update_product/<int:pk>/', views.update_user_product, name='user_update_product'),
    path('user_delete_product/<int:pk>/', views.DelUserProductView.as_view(), name='user_delete_product'),

]

shop/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Product, ExtraImage, SubCategory


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'form-control'}), label='Qnt:', min_value=0)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)


# Add Product form ----------------------------------------------------------------
class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('views',)
        widgets = {
            'author': forms.HiddenInput,
            'desctiption': CKEditorUploadingWidget(),
            'info': CKEditorUploadingWidget(),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'slug': forms.TextInput(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'thumbnail': forms.FileInput(attrs={'class':'form-control'}),
            'price': forms.NumberInput(attrs={'class':'form-control'}),
        }


# Extra images form for product form --------------------------------------------------
ExtraImageForm = forms.inlineformset_factory(Product, ExtraImage, fields='__all__', extra=5, can_delete_extra=False, widgets={
    'image': forms.FileInput(attrs={'class': 'form-control'})
    })

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
from .models import ExtraImage, Order, Product, SubCategory, SuperCategory, IpModel, IpCategory, About, Carousel
from .forms import CartAddForm, AddProductForm, ExtraImageForm
from .cart import Cart


# fist shop page -------------------------------------------
def shop(request):
    about = About.objects.get(show=True)
    carousel = about.carousel_set.all()
    products = Product.objects.order_by('-created_at')[:6]
    products_viewed = Product.objects.order_by('-views')[:4]
    cats_viewed = SubCategory.objects.order_by('-views')[:6]
    context = {'products': products,
               'products_viewed': products_viewed, 'cats_viewed': cats_viewed, 'about':about, 'carousel':carousel}
    return render(request, 'shop/shop.html', context)


# list products --------------------------------
class ProductView(ListView):
    paginate_by = 8
    model = Product
    template_name = 'shop/shop_products.html'
    context_object_name = 'products'

# product detail --------------------------------


def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    same_products = Product.objects.filter(name__icontains=product.name.split()[0])[:6]
    product_name = product.name.split()[0]
    author_products = Product.objects.filter(author=product.author)[:6]
    eis = product.extraimage_set.all()
    cart_form = CartAddForm()

    ip = get_ip(request)
    s = slug
    results = IpModel.objects.filter(ip=ip, product=s)
    if results.exists():
        print(results)
    else:
        IpModel.objects.create(ip=ip, product=s)
        product.views = product.views + 1
        product.save()
        print('user is unique', results)

    context = {'product': product, 'eis': eis, 'cart_form': cart_form,
               'same_products': same_products, 'p': product_name, 'author_products': author_products}
    return render(request, 'shop/shop_detail.html', context)


# categories page -------------------------------------
class CategoriesView(ListView):
    model = SuperCategory
    template_name = 'shop/shop_categories.html'
    context_object_name = 'cats'


# Subcategories page -------------------------------------
def sub_categories(request, pk):
    current_super_category = SuperCategory.objects.get(pk=pk)
    sub_categories = SubCategory.objects.filter(sup_category=pk)
    context = {'current_super_category': current_super_category,
               'sub_categories': sub_categories}
    return render(request, 'shop/shop_sub_categories.html', context)


# by_subcategories page -------------------------------------
def by_category(request, pk):
    products = Product.objects.filter(category=pk)
    current_cat = SubCategory.objects.get(pk=pk)
    paginator = Paginator(products, 8)

    if 'page' in request.GET:
        page_num = request.GET.get('page')
    else:
        page_num = 1
    page_obj = paginator.get_page(page_num)

    ip = get_ip(request)
    s = pk
    results = IpCategory.objects.filter(ip=ip, sub_categories=s)
    if results.exists():
        print(results)
    else:
        IpCategory.objects.create(ip=ip, sub_categories=s)
        current_cat.views = current_cat.views + 1
        current_cat.save()
        print('user is unique', results)

    context = {'products': page_obj.object_list,
               'current_cat': current_cat, 'page_obj': page_obj}
    return render(request, 'shop/shop_by_category.html', context)


# add cart ----------------------------------------------
@require_POST
def add_cart(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('shop:cart_detail')


def remove_cart(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    cart.remove(product)
    messages.success(request, 'Product has removed')
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['form'] = CartAddForm(
            initial={'quantity': item['quantity'], 'update': True})
    context = {'cart': cart}
    return render(request, 'shop/shop_cart.html', context)
# end card ------------------------------------------------


# Get user ip --------------------------------------------------------------------------
def get_ip(request):
    address = request.META.get('HTTP_X_FORWARDED_FOR')
    if address:
        ip = address.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


# Check out ------------------------------------------------------
class CartOrder(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        cart = request.session.get('cart')
        products = Product.objects.filter(pk__in=list(cart.keys()))
        for product in products:
            order = Order(
                product=Product.objects.get(pk=product.pk),
                customer=product.author,
                price=product.price,
                address=address,
                phone=phone,
                quantity=cart[str(product.id)]['quantity'],
            )
            order.place_order()
            request.session['cart'] = dict()
        messages.success(request, 'Your order has sent.')
        return redirect('shop:order_list')


# Order page ----------------------------------------
class OrderView(View):
    def get(self, request):
        customer = request.user.id
        orders = Order.customer_orders(customer)
        qs = []
        qp = []
        for s in orders:
            qs.append(s.quantity)
            q = s.quantity
            p = s.price
            qp.append(q*p)
        qs = sum(qs)
        qp = sum(qp)
        context = {'orders': orders, 'total_q': qs, 'total_p': qp}
        return render(request, 'shop/shop_order.html', context)


# shear list ---------------------------------------------------------
class Search(View):
    def get(self, request):
        keyword = request.GET.get('search')
        products = Product.objects.filter(name__icontains=keyword)
        paginator = Paginator(products, 4)
        if 'page' in request.GET:
            page_num = request.GET.get('page')
        else:
            page_num = 1
        page_obj = paginator.get_page(page_num)
        context = {'keyword': keyword,
                   'products': page_obj.object_list, 'page_obj': page_obj}
        return render(request, 'shop/shop_search_list.html', context)


# Add Product Form ----------------------------------------------
def add_product(request):
    form = AddProductForm()
    formset = ExtraImageForm()
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            formset = ExtraImageForm(
                request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
                messages.success(
                    request, 'The product has added successfully!')
                return redirect('shop:add_product')
        else:
            messages.warning(request, 'The product has not added try again!')

    else:
        form = AddProductForm(initial={'author': request.user.pk})
        formset = ExtraImageForm()
    context = {'form': form, 'formset': formset}
    return render(request, 'shop/shop_add_product.html', context)


# products by author-------------------------------------------------------------
def author_product(request, pk):
    products = Product.objects.filter(author=pk)
    paginator = Paginator(products, 4)
    if 'page' in request.GET:
        page_num = request.GET.get('page')
    else:
        page_num = 1
    page_obj = paginator.get_page(page_num)
    context = {'products': page_obj.object_list, 'page_obj': page_obj}
    return render(request, 'shop/author_products.html', context)


# user products --------------------------------------------------
class UserProductsView(ListView):
    paginate_by = 8
    template_name = 'shop/shop_user.html'
    context_object_name = 'products'

    def get_queryset(self):
        products = Product.objects.filter(author=self.request.user.pk)
        return products

# user detail product --------------------------------------------------
class UserDetailProductView(DetailView):
    template_name = 'shop/shop_user_detail_product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = DetailView.get_context_data(self, **kwargs)
        eis = self.product.extraimage_set.all()
        context['eis'] = eis
        return context

    def setup(self, request, *args, **kwargs):
        self.pk = kwargs['pk']
        return super().setup(request, *args, **kwargs)

    def get_object(self):
        self.product = Product.objects.get(pk=self.pk)
        return self.product


# update user product --------------------------------------------------
def update_user_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            formset = ExtraImageForm(

shop/templates/shop/shop.html
{% extends 'layout/basic.html'%}
{% load static %}

{% block title %}Shop{% endblock title %}

{% block content %}
<!-- Carousel --------------------------------------- -->
<div class="container-fluid">
    <div class="row justify-content-center">

        {% if carousel %}
        <div id="carouselExampleCaptions" class="carousel slide col-sm-8" data-bs-ride="false">
            <div class="carousel-inner">
                {% for c in carousel %}

                <div class="carousel-item active">
                    <img src="{{ c.image.url }}" class="d-block w-100" alt="...">
                    
                </div>
                {% endfor %}

            </div>
            <button class="carousel-control-prev" type="button"
                data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button"
                data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        {% else %}
        <h3 class="text-center text-secondary">Empty carousel</h3>
        {% endif %}
    </div>

    {% if about %}
    <div class="row mt-3 mb-5">
        <div class="card p-3 offset-sm-2 col-sm-8">
            <img src="{{ about.banner.url }}" alt="" class="card-img">
            <div class="card-img-overlay p-5 text-light ">
                <h3 class="card-title ">{{ about.name }}</h3>
                <a href="{% url 'shop:about' %}" class="btn btn-primary btn-lg">Read about</a>
            </div>
        </div>
    </div>
    {% else %}
    <h3 class="text-center text-secondary">Empty about</h3>

    {% endif %}
</div>
<!-- end carousel --------------------------------------- -->

<!-- main section --------------------------------------- -->

<section class="container pb-5">
    <div class="row mt-3">

        <h3 class="">Latest <a href="{% url 'shop:products' %}">See all</a></h3>
        {% if products %}
        {% for product in products %}
        <div class="col-lg-2 col-md-4 col-sm-6 mt-3">
            <div class="card">
                <img src="{{ product.thumbnail.url }}" alt="" class="img-fluid">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ product.name }}
                    </h5>
                    <aside>{{ product.price }} $</aside>
                    <a href="{{ product.get_absolute_url }}" class="stretched-link">Watch</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h3 class="text-center text-secondary">Empty</h3>
        {% endif %}
    </div>
    <div class="row mt-5">
        <h3 class="">Most popular <a href="{% url 'shop:viewed_product' %}">See all</a></h3>
        {% if products %}

        {% for p_viewed in products_viewed %}
        <div class="col-lg-3 col-md-6 mt-3">
            <div class="card">
                <img src="{{ p_viewed.thumbnail.url }}" alt="" class="img-fluid">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ p_viewed.name }}
                    </h5>
                    <aside>{{ p_viewed.price }} $</aside>
                    <a href="{{ p_viewed.get_absolute_url }}" class="stretched-link">Watch
                        <i class="bi bi-eye"></i> {{ p_viewed.views }}

                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h3 class="text-center text-secondary">Empty</h3>
        {% endif %}
    </div>

    <div class="row mt-5">
        <h3 class="">Popular Category <a href="{% url 'shop:viewed_category' %}">See all</a>
        </h3>
        {% if products %}
        
        {% for cat_viewed in cats_viewed %}
        <div class="col-lg-2 col-md-4 col-sm-6 mt-3">
            <a href="{% url 'shop:by_category' cat_viewed.pk %}"><img
                    src="{{ cat_viewed.image.url }}" alt=""
                    class="img-thumbnail rounded-circle"></a>
            <h5 class="text-center"><a href="">{{ cat_viewed.name }}</a></h5>
        </div>
        {% endfor %}

        {% else %}
        <h3 class="text-center text-secondary">Empty</h3>
        {% endif %}
    </div>
</section>
<!-- end main section --------------------------------------- -->

{% endblock content %}

shop/templates/shop/shop_detail.html
{% extends 'layout/basic.html' %}
{% load bootstrap5 %}

{% block title %}Shop::Product:{{ product.name }} {% endblock title %}


{% block content %}
<!-- main section --------------------------------------- -->

<section class="container pb-5">
    <div class="row align-items-center mt-3 mx-2">
        <img src="{{ product.thumbnail.url }}" alt="" class="img-thumbnail col-lg-2" width="100px">
        <h3 class="my-3 display-4 d-inline-block col-lg-10">{{ product.name }}</h3>
    </div>
    <div class="row mt-3 mx-1">
        
        <!-- Carousel --------------------------------------------- -->
        <div class="col-lg-6 border p-3 rounded-3">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for ei in eis %}
                    <div class="carousel-item active">
                        <img src="{{ ei.image.url }}" class="d-block w-100 img-fluid" alt="...">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <!-- end carousel --------------------------------------------- -->

        <div class="col-lg-6 border rounded-3">
            <div class="row ps-3 pe-3">
                <div class="col-lg-12">
                    <h1 class="mt-5 display-5">{{ product.name }}</h1>
                    <h3 class=" display-6 fs-3">price: {{ product.price }} $</h3>

                    <form action="{% url 'shop:add_cart' product.id %}" method="post" class="row my-3">
                        {% csrf_token %}

                        <label for="{{ cart_form.quantity.id_for_label }}" class="col-lg-2 col-form-label">{{ cart_form.quantity.label }}</label>

                        <div class="col-lg-6 p-0 mb-3 me-2">

                            {{ cart_form.quantity }}
                            {{ cart_form.update }}
                        </div>

                        <input type="submit" class="btn btn-primary col-lg-3 mb-3" value="Add to cart">
                    </form>
                    <hr class="border-primary">
                    <div class="display-6 fs-5">
                        <aside>Added: {{ product.created_at }}</aside>
                        <hr class="border-primary">
                        <aside>Category: <a href="{% url 'shop:by_category' product.category.pk %}">{{ product.category }}</a></aside>
                        <hr class="border-primary">
                        <aside>Author: {{ product.author }}</aside>
                        <hr class="border-primary">
                    </div>


                    
                    <aside class="mb-3"><i class="bi bi-eye"></i> {{ product.views }}</aside>
                </div>

            </div>
        </div>
    </div>

    <div class="row mt-5 mx-1">
        <div class="card p-0">
            <div class="card-header">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs card-header-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-bs-toggle="tab" href="#home">Description</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#menu1">About</a>
                    </li>
                
                </ul>
            </div>
            <card class="body mt-2">


                <!-- Tab panes -->
                <div class="tab-content mb-3">
                    <div id="home" class="container tab-pane active overflow-auto ">
                        <br>
                        {{ product.description|safe }}
                    </div>
                    <div id="menu1" class="container tab-pane fade overflow-auto">
                        <br>
                        {{ product.info|safe }}
                    </div>
                    
                </div>
            </card>
        </div>
    </div>

    <div class="row mt-5 border-top pt-3">
        <h3 class="">All author's products
            <a href="{% url 'shop:author_product' product.author.pk %}">see all</a>
        </h3>

        

        {% for author_product in author_products %}
        <div class="col-lg-2 col-md-4 col-sm-6 mt-3">
            <div class="card">
                <img src="{{ author_product.thumbnail.url }}" alt="" class="img-fluid">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ author_product.name }}
                    </h5>
                    <aside>{{ author_product.price }}$</aside>
                    <a href="{{ author_product.get_absolute_url }}" class="stretched-link">Watch</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    <div class="row mt-5 border-top pt-3">
        <h3 class="">The same products
            <form action="{% url 'shop:search' %}" class="d-inline-block">
                <input type="hidden" class="form-control me-3" name="search" value="{{p}}">
                <input class="border-0 bg-light text-primary" type="submit" value="See all"></input>
            </form>
        </h3>

        

        {% for same_product in same_products %}
        <div class="col-lg-2 col-md-4 col-sm-6 mt-3">
            <div class="card">
                <img src="{{ same_product.thumbnail.url }}" alt="" class="img-fluid">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ same_product.name }}
                    </h5>
                    <aside>{{ same_product.price }}$</aside>
                    <a href="{{ same_product.get_absolute_url }}" class="stretched-link">Watch</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>


</section>
<!-- end main section --------------------------------------- -->
{% endblock content %}

shop/templates/shop/shop_user_detail_product.html
{% extends 'layout/basic.html' %}
{% load bootstrap5 %}



{% block title %} Shop::{{ request.user.username }} product:{{ product.name }} {% endblock title %}

{% block content %}



<!-- main section --------------------------------------- -->

<section class="container pb-5">

    {% if messages %}
    {% for message in messages %}

    <div class="alert {{ message.tags }} mt-3 alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
    {% endfor %}
    {% endif %}


    <div class="row align-items-center mt-3 mx-2">
        <img src="{{ product.thumbnail.url }}" alt="" class="img-thumbnail col-lg-2" width="100px">
        <h3 class="m-0 display-4 d-inline-block col-lg-10">{{ product.name }}</h3>
    </div>
    <div class="row mt-3 mx-1">

        <!-- Carousel --------------------------------------------- -->
        <div class="col-lg-6 border p-3 rounded-3">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for ei in eis %}
                    <div class="carousel-item active">
                        <img src="{{ ei.image.url }}" class="d-block w-100" alt="...">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button"
                    data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button"
                    data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <!-- end carousel --------------------------------------------- -->

        <div class="col-lg-6 border rounded-3">
            <div class="row ps-3 pe-3">
                <div class="col-lg-12">
                    <h1 class="mt-5 display-5">{{ product.name }}</h1>
                    <h3 class=" display-6 fs-3">price: {{ product.price }} $</h3>

                    <hr class="border-primary">
                    <div class="display-6 fs-5">
                        <aside>Added: {{ product.created_at }}</aside>
                        <hr class="border-primary">
                        <aside>Category: <a
                                href="{% url 'shop:by_category' product.category.pk %}">{{product.category
                                }}</a></aside>
                        <hr class="border-primary">
                        <aside>Author: {{ product.author }}</aside>
                        <hr class="border-primary">
                    </div>



                    <aside><i class="bi bi-eye"></i> {{ product.views }}</aside>


                    <div class="mt-3 mb-3">
                        <a href="{% url 'shop:user_update_product' product.pk %}"
                            class="btn btn-success">Update</a>
                        <a href="{% url 'shop:user_delete_product' product.pk %}"
                            class="btn btn-danger">Delete</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row mt-5 mx-1">
        <div class="card p-0">
            <div class="card-header">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs card-header-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-bs-toggle="tab" href="#home">Description</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#menu1">About</a>
                    </li>

                </ul>
            </div>
            <card class="body mt-2">


                <!-- Tab panes -->
                <div class="tab-content mb-3">
                    <div id="home" class="container tab-pane active overflow-auto"><br>
                        <h3>Description</h3>
                        <p>{{ product.description|safe }}</p>
                    </div>
                    <div id="menu1" class="container tab-pane fade overflow-auto"><br>
                        <h3>About</h3>
                        <p>{{ product.info|safe }}</p>
                    </div>
                   
                </div>
            </card>
        </div>
    </div>



</section>
<!-- end main section --------------------------------------- -->
{% endblock content %}